-- AlterTable
ALTER TABLE "ExamAttempt" ADD COLUMN     "questionOrder" JSONB,
ALTER COLUMN "score" DROP NOT NULL,
ALTER COLUMN "total" DROP NOT NULL,
ALTER COLUMN "passed" DROP NOT NULL,
ALTER COLUMN "answers" DROP NOT NULL,
ALTER COLUMN "startedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "submittedAt" DROP NOT NULL;
